---
version: '3.7'

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=performer
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database:/data/db
    ports:
      - '27017-27019:27017-27019'
